### ISSUE TITLE
Use of uninitialized value 

### ISSUE THREAD

**Issue by zhangzhen999** [DevSinghSachan/multilingual_nmt#4]
python: symbol lookup error: /usr/local/python3/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
BPE decoding/detokenising target to match with references
Step 4a: Evaluate Test
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
Step 4b: Evaluate Dev
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
[root@79dd8fc

**Comment by DevSinghSachan** [comment]
Could you paste the run command here and also give a brief description of the system environment so that I can reproduce this error.

**Comment by zhangzhen999** [comment]
description of my computer system environment:
Tesla P100

>>cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

nvidia-smi 384.81

CUDA Version 9.0.176

tensorflow-gpu==1.8.0

torch version==0.4.1

can you give a brief description of the system environment so that I can reproduce the multilingual_nmt test.

**Comment by DevSinghSachan** [comment]
This looks like an error related to the .so file. Could you try to install the various dependencies on top of conda environment.
