### ISSUE TITLE
unicodeDecodeError

### ISSUE THREAD

**Issue by zhangzhen999** [DevSinghSachan/multilingual_nmt#5]
unicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 904: ordinal not in range(128) [root@ccb234d5f670 multilingual_nmt]

**Comment by DevSinghSachan** [comment]
Could you paste the run command here and also give a brief description of the system environment so that I can reproduce this error.

**Comment by zhangzhen999** [comment]
这个问题我已经解决了,我的解决办法如下：
$ sudo vi /etc/profile
按a或i进入编辑模式
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
按Esc键退出编辑模式
:wq (保存并退出)
$ source /etc/profile

**Comment by zhangzhen999** [comment]
I have solved this problem, my solution is as follows:
$ sudo vi /etc/profile
Press a or i to enter edit mode
Export LANG='en_US.UTF-8'
Export LC_ALL='en_US.UTF-8'
Press Esc to exit edit mode
:wq (save and exit)
$ source /etc/profile

**Comment by DevSinghSachan** [comment]
Great, so I am closing this issue for now!
