### ISSUE TITLE
CUDA version is insufficient

### ISSUE THREAD

**Issue by zhangzhen999** [DevSinghSachan/multilingual_nmt#6]
I enconter a question,CUDA version is insufficient,the error logs display as follows:
/usr/local/python3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
* number of parameters: 42336897
encoder:  9452032
decoder:  12600832
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtimeversion
Traceback (most recent call last):
  File "/home/work/notebooks/multilingual_nmt-master/train.py", line 457, in <module>
    main()
  File "/home/work/notebooks/multilingual_nmt-master/train.py", line 209, in main
    model.cuda(args.gpu)
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74
BPE decoding/detokenising target to match with references
Step 4a: Evaluate Test
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
Step 4b: Evaluate Dev
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.
Use of uninitialized value $length_reference in numeric eq (==) at /home/work/notebooks/multilingual_nmt-master/tools/multi-bleu.perl line 148.

environment :centos7
run command:
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
bash download_teddata.sh
python ted_reader.py -s ja en zh fr ro -t en zh fr ro ja
python ted_reader.py -s ja en zh fr ro -t en zh fr ro ja -ncp
bash tools/bpe_pipeline_bilingual.sh src_lang tgt_lang

**Comment by DevSinghSachan** [comment]
It seems to me that it's a CUDA toolkit and NVIIDA driver version mismatch. Are you able to run other code using pytorch?
