### ISSUE TITLE
How to tokenize the multilingual text corpus?

### ISSUE THREAD

**Issue by Encyclomen** [DevSinghSachan/multilingual_nmt#8]
After running python ted_reader.py -s zh ja -t en, I obtain the multilingual corpus. But before learning BPE, I need to tokenize the corpus composed of several different languages such as japanese, chinese and english. The script tokenizer.perl does not seem to work. How can I tokenize the multilingual text?

**Comment by DevSinghSachan** [comment]
Yeah, there might be an issue with languages such as Japanese, Korean etc. which do not use whitespace. One option that I have also used in the paper is to pre-tokenize Japanese text with the KyTea tokenizer (http://www.phontron.com/kytea/), using its word segmentation feature. And then apply Byte-Pair Encoding approach to learn the vocabularies. Hope this helps!
